### ISSUE TITLE
can't find '__main__' module in 'halberd'

### ISSUE THREAD

**Issue by blueelvis** [jmbr/halberd#4]
Hi,

You fixed this issue over here - https://github.com/jmbr/halberd/issues/3

The program got installed successfully. Now, when I type in `python halberd google.com`, I get the following error -

`E:\dev\halberd>python halberd google.com`
`C:\Python27\python.exe: can't find '__main__' module in 'halberd'`

**Comment by jmbr** [comment]
I cannot reproduce this bug as I don't have any available machine running Windows on which to run tests. The installation certainly works fine in Linux. Perhaps this is a problem with your PYTHONPATH environment variable?
